### ISSUE TITLE
Use Specific Nightly Icon versus stable vlc app icon

### ISSUE THREAD

**Issue by rancidfrog** [GeoffreyMetais/vlc-android#5]
I believe a while ago vlc had different icons for both, black/white vs colour or b for beta.
It would be great to have some sort of difference to distinguish between stable build and nightly, colour/letter not sure not designer. 
I am sure theme community would be willing to help,
221 pixels recently did overhauls of default icon pack for DU Rom and a new icon for substratum theme platform: https://plus.google.com/105386924007076792931/posts/TtLZRG63pMC

**Comment by GeoffreyMetais** [comment]
Fixed by 9ecaa0a

We should have done that years ago...
