### ISSUE TITLE
Loading videos takes long time even just switching from horizontal to vertical layout

### ISSUE THREAD

**Issue by rancidfrog** [GeoffreyMetais/vlc-android#6]
When in videos view:
![](https://s11.postimg.org/47rgd3j3n/20170301_121933.jpg)
Just switch from one layout to another causes blank reload icon.
![](https://s16.postimg.org/7gs2dwkl1/20170301_121947.jpg)
Also switching tabs and on app relaunch, video grid takes time even when grouping disabled.

**Comment by GeoffreyMetais** [comment]
VLC 2.1.1?
What's your device and how many videos do you have?

It should be quick, even with a large media library

**Comment by rancidfrog** [comment]
Yes, vlc 2.1.1 
It also occurs when videos ends and screen returns to video view.
Videos around 50-100.
Device sony z3 compact

**Comment by rancidfrog** [comment]
One note,
I have in Advanced settings - Auto rescan disabled.
Yet the loading icon every time appears on launch and when video ends and grid is redisplayed.
(So, I do not believe it actually checks anything, just the library used for view is a little slow and keeps showing loading animation when not necessary as there is nothing to do when returning to grid after video playback ends but still animation shows on top of grid for a few seconds)
