### ISSUE TITLE
[Feature[ Sorting video queue playback

### ISSUE THREAD

**Issue by rancidfrog** [GeoffreyMetais/vlc-android#7]
Currently there is no way to order video queue
Neither
- Order which video is selected
Nor
- Sorting queue

It would be ideal to have a way to sort playback order
I.E. Below example is from AIMP music player, after clicking sort button boxes appear which can be dragged to order:
![](https://s17.postimg.org/4jydrkfhb/Screenshot_20170310_134033.png)
**Also, having items numbered can be useful**

**Comment by GeoffreyMetais** [comment]
You can drag&drop videos in current playlist
